export type User = {
  id: string;
  name: string;
  email: string;
  role: string;
  permissions: string[];
};
export type Terms = {
  applicant: string;
  beneficiary: string;
  applicant_country: string;
  beneficiary_country: string;
  issuing_bank: string;
  advising_bank: string;
  confirming_bank: string;
  lc_type: string;
  currency: string;
  amount: string;
  tolerance_pct: string;
  tolerance_amount: string;
  issue_date: string;
  expiry_date: string;
  latest_shipment: string;
  presentation_date: string;
  presentation_period: number;
  loading_port: string;
  discharge_port: string;
  place_of_expiry: string;
  incoterm: string;
  goods: string;
  quantity: string;
  quantity_unit: string;
  unit_price: string;
  payment_terms: string;
  partial_shipment: boolean;
  transshipment: boolean;
  required_documents: string[];
  special_conditions: string;
  rule_profile: string;
};
export type Result = {
  rule_id: string;
  rule_name: string;
  category: string;
  severity: string;
  status: string;
  expected_value: string;
  actual_value: string;
  explanation: string;
  recommendation: string;
  rule_version: number;
  evidence: {
    document_id: string;
    type: string;
    version: number;
    number: string;
  }[];
};
export type Doc = {
  id: string;
  type: string;
  number: string;
  filename: string;
  sha256: string;
  version: number;
  size: number;
  uploaded_at: string;
  uploaded_by: string;
  fields: Record<string, unknown>;
  reason: string;
};
export type Finding = {
  id: string;
  lc_id: string;
  run_id: string;
  rule_id: string;
  severity: string;
  status: string;
  result: Result;
  decision: string;
};
export type Audit = {
  id: number;
  timestamp: string;
  actor: string;
  role: string;
  action: string;
  entity_id: string;
  details: Record<string, unknown>;
  event_hash: string;
  previous_hash: string;
  correlation_id: string;
};
export type LC = {
  id: string;
  reference: string;
  title: string;
  terms: Terms;
  status: string;
  priority: string;
  version: number;
  terms_version: number;
  risk_score: number;
  risk_band: string;
  risk_factors: { label: string; points: number }[];
  sla: string;
  due_at: string;
  created_at: string;
  updated_at: string;
  assigned_to: string | null;
  assignee_name?: string;
  allowed_actions?: string[];
  review_checklist?: string[];
  documents?: Doc[];
  validation?: {
    id: string;
    created_at: string;
    results: Result[];
    risk: { score: number; band: string };
  };
  discrepancies?: Finding[];
  comments?: {
    id: string;
    body: string;
    actor_name: string;
    created_at: string;
  }[];
  decisions?: {
    id: string;
    action: string;
    reason: string;
    actor_id: string;
    created_at: string;
  }[];
  versions?: {
    id: string;
    version: number;
    reason: string;
    created_at: string;
    terms: Terms;
  }[];
  audit?: Audit[];
  checklist: string[];
};
export type Page<T> = { items: T[]; total: number; page: number };
export type Dashboard = {
  total: number;
  open: number;
  pending_review: number;
  approved: number;
  high_risk: number;
  sla_breaches: number;
  average_hours: number;
  approval_rate: number;
  discrepancies: number;
  overrides: number;
  status_distribution: Record<string, number>;
  risk_distribution: Record<string, number>;
  sla_distribution: Record<string, number>;
  discrepancy_categories: Record<string, number>;
  rule_failures: Record<string, number>;
  trend: { date: string; label: string; cases: number; flagged: number }[];
  attention: LC[];
  recent: LC[];
  generated_at: string;
};
export type Rule = {
  id: string;
  name: string;
  category: string;
  description: string;
  severity: string;
  enabled: boolean;
  version: number;
};
export type Notice = {
  id: string;
  lc_id: string | null;
  message: string;
  read: boolean;
  created_at: string;
};
